### ISSUE TITLE
Please download the kitty executable not in the plugin folder

### ISSUE THREAD

**Issue by taooceros** [lostping/Flow.Launcher.Plugin.Kitty#3] opened 2022-01-26 23:51 UTC
The update mechanism of flow will delete the old version and download the new version into the plugin folder, so currently every time we update kitty will remove the kitty executable and session information.

We recommend storing it in flow's userprofile, which may vary if user enable portable mode. So you may need to check whether the from ../../UserData/Settings/Plugins/Plugin Name exists (which is portable mode), or %appdata%/FlowLauncher/Settings/Plugins/Plugin Name, which is the same path for the jsonsetting.

**Comment by lostping** [comment] 2022-01-27 04:50
Actually it is the intention to remove everything when uninstalled, but I didn't think of the updates.
(I won't flag this issue as bug, because this was the intended behavior.)

But I understand that's quite a nuisance when someone uses the portable mode.
Thanks for bringing this issue to my attention. I'll check options and the next version will use flow's userprofile folder.

**Comment by taooceros** [comment] 2022-01-27 19:17
Thank you!

**Comment by lostping** [comment] 2022-01-30 16:43
Fixed with [#a4000f3](https://github.com/lostping/Flow.Launcher.Plugin.Kitty/commit/a4000f31fe6dcf7dbe50bfd05b02b89d5220f4d2)

**Closed as completed by lostping** 2022-01-30 16:43 UTC
Labels: enhancement
